### ISSUE TITLE
Automating Script

### ISSUE THREAD

**Issue by tstrogers** [tstrogers/EC601#3]
The exe file created from the script is producing different results when ran from the terminal compared to when it is run from the IDE. Values are not being stored/saved as expected which could be due to poor module/IDE setup.

**Comment by tstrogers** [comment]
Traceback (most recent call last):
  File "pandas/core/indexes/base.py", line 3800, in get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

**Comment by tstrogers** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Project2.py", line 189, in <module>
  File "pandas/core/series.py", line 982, in __getitem__
  File "pandas/core/series.py", line 1092, in _get_value
  File "pandas/core/indexes/base.py", line 3802, in get_loc
KeyError: 1
[56908] Failed to execute script 'Project2' due to unhandled exception!
